ICU-21360 Fix false true in ICU-demos
unicode-org/icu-demos pull request #21
Opened 2020-10-29 01:51 UTC by sven-oly

This updates the code in icu-demos to use true/false rather than TRUE/FALSE, which were updated in ICU4C sources in ICU-21267.

2020-10-29 13:26 UTC, roubert requested changes
It looks to me as if you missed a lot of instances so I've now uploaded a new commit to this PR to fix those too, please review that commit to verify that none of those were omitted intentionally.

2020-10-29 13:26 UTC, roubert commented on test/obstest/intltest.h
> +Copyright:
There are some spurious changes to the copyright comment here, unrelated to the rest of the PR, please revert.

2020-10-29 13:26 UTC, roubert commented on test/obstest/ucdtest.cpp
> +        multiple=(UBool)(codepoint[i] == 1 ? false : true);
I think this would be an excellent opportunity to simplify this statement to:

```c++
multiple = codepoint[i] != 1;
```

2020-10-29 13:26 UTC, roubert commented on webdemo/collation/build.sh
> +HOME=/usr/local/google/home/ccornelius/ICU68_release
Please revert all changes to this file.

2020-10-29 13:26 UTC, roubert commented on webdemo/collation/index.html
> +<option value="br">br (type=standard):   Breton (Standard Sort Order)</option>
These might (or might not) be changes that ought to be done, but not as part of this PR, please revert.

2020-10-29 13:26 UTC, roubert commented on locexp/srchexp.c
> +    return false`;
This is a typo (and won't compile).

2020-10-29 14:04 UTC, srl295 commented on webdemo/collation/index.html
> +<option value="br">br (type=standard):   Breton (Standard Sort Order)</option>
@roubert I think this is actually a generated file, and changes when the build process makes a change.  As such it could probably be .gitignor'ed

2020-10-29 14:05 UTC, srl295 commented on locexp/srchexp.c
> +    return false`;
```suggestion
    return false;
```

2020-10-29 14:20 UTC, markusicu commented on webdemo/collation/index.html
> +<option value="br">br (type=standard):   Breton (Standard Sort Order)</option>
This file is indeed generated, and then manually put into a PR.
Looks like Craig did so as part of this one.
I am ok with Fredrik's request to make single-purpose PRs -- that's indeed cleaner.

2020-11-11 15:13 UTC, srl295 approved these changes

2020-11-11 15:57 UTC, roubert commented
> It looks to me as if you missed a lot of instances so I've now uploaded a new commit to this PR to fix those too, please review that commit to verify that none of those were omitted intentionally.

So you used a force push to overwrite this commit. I can only assume that this was a mistake, so I've now uploaded this commit to this PR again. Please review it to verify that none of those were omitted intentionally.

2020-11-11 16:11 UTC, srl295 commented
> > It looks to me as if you missed a lot of instances so I've now uploaded a new commit to this PR to fix those too, please review that commit to verify that none of those were omitted intentionally.
> 
> So you used a force push to overwrite this commit. I can only assume that this was a mistake, so I've now uploaded this commit to this PR again. Please review it to verify that none of those were omitted intentionally.

This isn't ICU. I think we can use multiple commits, so there's no reason to rebase/force push.

2020-11-11 17:15 UTC, sven-oly commented on icu-kube/docker.d/icu4c-demos/Dockerfile
> +RUN mkdir -p /home/build/build /home/build/src
Done.

2020-11-11 17:20 UTC, sven-oly commented on convexp/convexp.cpp
> +    printf("<tr><th>Is ASCII [\\x20-\\x7E] compatible?</th><td>%s</td></tr>\n", (isASCIIcompatible(cnv) ? "true" : "false"));
Done

2020-11-11 17:20 UTC, sven-oly commented on convexp/convexp.cpp
> +    printf("<tr><th>Is ASCII [\\x20-\\x7E] compatible?</th><td>%s</td></tr>\n", (isASCIIcompatible(cnv) ? "true" : "false"));
Done. Thanks for catching.

2020-11-11 17:26 UTC, sven-oly commented on test/obstest/intltest.h
> +Copyright:
Done

2020-11-11 17:30 UTC, sven-oly commented on webdemo/collation/build.sh
> +HOME=/usr/local/google/home/ccornelius/ICU68_release
Done

2020-11-11 17:31 UTC, sven-oly commented on locexp/srchexp.c
> +    return false`;
Typo fixed

2020-11-11 17:39 UTC, sven-oly commented on webdemo/collation/index.html
> +<option value="br">br (type=standard):   Breton (Standard Sort Order)</option>
I've removed these updates. These will be done in another update for collation demo.

2020-11-11 17:40 UTC, sven-oly commented
Yes, my push last evening was a mistake. Thank you, Fredrik, for fixing the additional instances and pushing your update again.

I've also updated other items as suggested.

2020-11-11 17:44 UTC, sven-oly commented
I would be happy to squash if desired.

2020-11-11 18:11 UTC, sven-oly commented on test/obstest/ucdtest.cpp
> +        multiple=(UBool)(codepoint[i] == 1 ? false : true);
Good idea. Done.

2020-11-11 23:30 UTC, roubert commented
> Thank you, Fredrik, for fixing the additional instances and pushing your update again.

Have you now reviewed my changes, were they all changes that you had omitted by mistake?

2020-11-11 23:30 UTC, roubert requested changes
This commit 12d0a6281d9fcabf11e44e264e2e9a65e27f124e reverted-reverted one step too far, you should be reverting commit 832167c8b9c63a143b5a3caba76fc070aed182e3 from PR #20 (Workaround for ICU-21267) here together with removing the need for that workaround.

2020-11-18 18:02 UTC, sven-oly commented on icu-kube/docker.d/icu4c-demos/Dockerfile
> +RUN mkdir -p /home/build/build /home/build/src
Thanks for catching these, Fredrik. I've reviewed your updates. All look OK.

2020-11-18 18:56 UTC, roubert requested changes

2020-11-18 18:56 UTC, roubert commented on locexp/srchexp.c
> +    return false`;
Now it has become unfixed, please fix it again. (If you don't, this code won't compile, so it really matters.)

2020-11-18 19:25 UTC, roubert approved these changes

2020-11-18 19:26 UTC, merged